name: coverage

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          sudo apt install python3-tk -y
          python -m pip install --upgrade pip
          pip install pytest pylint coverage
          pip install -r requirements.txt
      
      - name: Generate coverage
        run: |
          coverage run

      - name: Generate JSON coverage report
        run: |
          coverage json

      - name: Check coverage threshold
        run: |
          ./check_coverage.py
